apiVersion: v1
baseDomain: steve-aws.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp4-terra
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    cluster: mycluster
    datacenter: Datacenter
    defaultDatastore: datastore1
    network: VM Network
    password: whSY*0805*
    username: administrator@vsphere.local
    vCenter: vcsa.saltware.lab
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNzBiOTA2ZDg0YmQ5NDkzN2JlMGM4MjQwNTExMzg0OWU6SjJFS0dMMFNMSU1MUkVKS0ZPUTFPNUNMSk9JUVQzSlZOUlFOVkNXOVcwM1pPM0dLVEtNTVpDNDMxMkpYNkFCQQ==","email":"whpark@saltware.co.kr"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNzBiOTA2ZDg0YmQ5NDkzN2JlMGM4MjQwNTExMzg0OWU6SjJFS0dMMFNMSU1MUkVKS0ZPUTFPNUNMSk9JUVQzSlZOUlFOVkNXOVcwM1pPM0dLVEtNTVpDNDMxMkpYNkFCQQ==","email":"whpark@saltware.co.kr"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTJlNTIyMDRkLWVmNjAtNDhlNC04YWQ4LWU0N2U2MzFiYjUxNTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhZamhqTnpjeE5XTmpZVEkwWTJKbU9HRmhPVEU0TlRneU1HSm1NbUk0TnlKOS5HaWJ2ell6MklqNGV1MXExN3o4dGI4cTFrZUdtbGJDODB6RUVuT1FTc3VLOE5JNERycUktd2VpWDZlRk5LXy00TXh2Q3Zsd1BkbkhnYjR5UWJVemprSzBCTThSaU1zbHNYTU5aWUxVZG8wNm5sRGZ0U3BuWG1GcjVnd2dPY2JXV3FpTkxpc1ZsZ3h6QnFtVjVmeUE1YXU3LVZ3QzNWY01JR083Q2VoelVqdjlPMlkyZEtXemtUUV94eVdHeWx3VTlwUjctWFlxMUQ2UmlycTBHQks1YXVZUlV4WVJLVWVNcjlxUzVNbHJPZ3EzOS1HaldHV2xpSHNwajhqeWppaFB3Rkxmb1NmZkYtRVFRcUtORC1ueDh0cDJ2eVkwdHVqRjcwZTdBYi1YSFZ3QVBZUDBfRkJSUm1MOXVJS3FSRll1ZTVETXpqRWtRUG1ZT01yRTMtNkJBeUJUb3hlMkpZRWJneVRZZHluT0RPNlZjRWpGLWRMSGFwby04UmRfRXRaSVRmNFJPSW5uZHpUdWllUmt0NllHQzBtWUZMbWpYQ21YMGI0cTM3cVFNS3dyX254c2xnWG1nNmhWdHp5ODdMc01NUGRFMFllTFVoZVpWbFdrNGtCaVZ2RGZqNXd5bjJyTUlRU0VqSWYweFg3N1ZzNm8yak83U1FrcFZrVm5ENmtyei1Vb0lSRFE4Wk1ZNTJwbGFZMnRUMUhUQWJZR2FWQ1NYZjZ0TVdBQ2NZN0pvcm1hb2NOWFFGRDBIZXpuZFh4MXBSamJjd2o4SjJWV0J1UWJLTGhiT1p2X2Y4UWZLV1p0NXJWMkRKaFkwZXJSSE9VbTk0YzlILWdJcl9SelI5dURSLTJJN0dBa0gwbWRXZ0dxQkdrVHM5SlZIUTVCMW5mZkNuQTUwNzhEWTQyTQ==","email":"whpark@saltware.co.kr"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTJlNTIyMDRkLWVmNjAtNDhlNC04YWQ4LWU0N2U2MzFiYjUxNTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhZamhqTnpjeE5XTmpZVEkwWTJKbU9HRmhPVEU0TlRneU1HSm1NbUk0TnlKOS5HaWJ2ell6MklqNGV1MXExN3o4dGI4cTFrZUdtbGJDODB6RUVuT1FTc3VLOE5JNERycUktd2VpWDZlRk5LXy00TXh2Q3Zsd1BkbkhnYjR5UWJVemprSzBCTThSaU1zbHNYTU5aWUxVZG8wNm5sRGZ0U3BuWG1GcjVnd2dPY2JXV3FpTkxpc1ZsZ3h6QnFtVjVmeUE1YXU3LVZ3QzNWY01JR083Q2VoelVqdjlPMlkyZEtXemtUUV94eVdHeWx3VTlwUjctWFlxMUQ2UmlycTBHQks1YXVZUlV4WVJLVWVNcjlxUzVNbHJPZ3EzOS1HaldHV2xpSHNwajhqeWppaFB3Rkxmb1NmZkYtRVFRcUtORC1ueDh0cDJ2eVkwdHVqRjcwZTdBYi1YSFZ3QVBZUDBfRkJSUm1MOXVJS3FSRll1ZTVETXpqRWtRUG1ZT01yRTMtNkJBeUJUb3hlMkpZRWJneVRZZHluT0RPNlZjRWpGLWRMSGFwby04UmRfRXRaSVRmNFJPSW5uZHpUdWllUmt0NllHQzBtWUZMbWpYQ21YMGI0cTM3cVFNS3dyX254c2xnWG1nNmhWdHp5ODdMc01NUGRFMFllTFVoZVpWbFdrNGtCaVZ2RGZqNXd5bjJyTUlRU0VqSWYweFg3N1ZzNm8yak83U1FrcFZrVm5ENmtyei1Vb0lSRFE4Wk1ZNTJwbGFZMnRUMUhUQWJZR2FWQ1NYZjZ0TVdBQ2NZN0pvcm1hb2NOWFFGRDBIZXpuZFh4MXBSamJjd2o4SjJWV0J1UWJLTGhiT1p2X2Y4UWZLV1p0NXJWMkRKaFkwZXJSSE9VbTk0YzlILWdJcl9SelI5dURSLTJJN0dBa0gwbWRXZ0dxQkdrVHM5SlZIUTVCMW5mZkNuQTUwNzhEWTQyTQ==","email":"whpark@saltware.co.kr"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDokusUVFTmOCzg+mLM4ZEByssctQ1jsmnz3+Ct7PamMgwxL0s5py1euEW2b0FN33uyKRXa4IaAa+zO/XuKpJMxBnz+NpY/GHviJF7ceyb8oY4Od71+PdG1TWO2cCndjtC9ujU2bIXHvIc7gATzPLGAd94psZ94/2d8QxFHBge6r7DmtYR54H4vH7k6KsfKyAlquE4qfgqngxW1gvie2sdwtfttYO9jSpt4YsaHxvbTO00p2W04nxUXZLE8vecj3AGBu4sA59AVLswCODdSuB8w6CtbjdRytaH5VKROgPhTuTGktTPyW5QEIRZCtBjOhypHmAE3Je95Te7BPgMmwOYiOmuLSzZwmsTbqnawaIYyDXHrrinojTbqIhBC2MaFWP8ClIWQ4MUJIN2frJe5vHJqUsANLBGCbN+nM3OFOSUeCbuyJh/4GCo0CwaEFGFiz0etETyP3CnkH7gQkBa9aac5eO4QAt0RW/N6T66+tEhbwMdHh6Iyr/tmBeGqb3T+RLE= root@bastion.ocp4.steve-ml.net
